version: "3.2"

networks:
  indabox:

services:

  server:
      image: node:11.8-alpine
      container_name: indabox-server
      command: npm run dev
      working_dir: /home/server
      depends_on:
        - redis
        - mongo
      networks:
        - indabox
      ports:
        - "3000:3000"
        - "9229:9229"
      restart: unless-stopped
      volumes:
        - ./server:/home/server

  # client:
  #   image: node:11.8-alpine
  #   container_name: indabox-client
  #   command: npm run start
  #   working_dir: /home/client
  #   depends_on:
  #     - server
  #   environment:
  #       REACT_APP_API_URL: http://0.0.0.0:3000
  #   networks:
  #     - indabox
  #   ports:
  #     - "80:3000"
  #   restart: unless-stopped
  #   volumes:
  #     - ./client:/home/client

  mongo:
    image: mongo:4.1.7
    container_name: indabox-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    networks:
        - indabox
    ports:
      - "27017:27017"
    restart: unless-stopped

  redis:
    image: redis:5.0.3
    container_name: indabox-redis
    command: redis-server --appendonly yes --requirepass rootpw
    networks:
      - indabox
    ports:
      - "6379:6379"
    restart: unless-stopped
