version: '3.1'

services:

### INDABOX ##########################################

  indabox-mongo:
    image: mongo:4.1.7
    container_name: indabox-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./_data/indabox-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $root@user
      MONGO_INITDB_ROOT_PASSWORD: $root@password

  indabox-redis:
    image: redis:5.0.3
    container_name: indabox-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass $redis@password
    ports:
      - 6379:6379
    volumes:
      - ./_data/indabox-redis:/data

  indabox-server:
    image: node:11.8-alpine
    container_name: indabox-server
    restart: unless-stopped
    depends_on:
      - indabox-redis
      - indabox-mongo
    ports:
      - 8080:8080
    volumes:
      - ./indabox-server:/var/www
    working_dir: /var/www
    command: sh -c "npm i && npm run start"
    environment:
      ROOT_EMAIL: $root@email
      ROOT_PASSWORD: $root@password
      DB_USER: $db@user
      DB_PASSWORD: $db@password
      REDIS_PASSWORD: $redis@password
      IFTHEN_ENTETY: $ifthen@entety
      IFTHEN_SUBENTETY: $ifthen@subentety
      IFTHEN_KEY: $ifthen@key


  indabox-client:
    image: node:11.8-alpine
    container_name: indabox-client
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - ./indabox-client:/var/www
    working_dir: /var/www
    command: sh -c "npm i && npm run start"
    environment:
      REACT_APP_API_URL: http://193.70.43.66:8080
