version: "3.2"

networks:
  indabox:

services:

  server:
      image: docker.pkg.github.com/car12o/indabox/server:${TAG}
      build:
        context: ./server
      container_name: indabox-server
      working_dir: /home/server
      depends_on:
        - redis
        - mongo
      environment:
        APP_NAME: indabox-server
        APP_PORT: 3000
        ROOT_EMAIL: ${ROOT_EMAIL}
        ROOT_PASSWORD: ${ROOT_PASSWORD}
        MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        IFTHEN_ENTETY: ${IFTHEN_ENTETY}
        IFTHEN_SUBENTETY: ${IFTHEN_SUBENTETY}
        IFTHEN_KEY: ${IFTHEN_KEY}
      networks:
        - indabox
      ports:
        - "3000:3000"
      restart: unless-stopped

  client:
    image: docker.pkg.github.com/car12o/indabox/client:${TAG}
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: indabox-client
    depends_on:
      - server
    networks:
      - indabox
    ports:
      - "80:80"
    restart: unless-stopped

  mongo:
    image: mongo:4.1.7
    container_name: indabox-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
        - indabox
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:5.0.3
    container_name: indabox-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - indabox
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
