version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:11.8-stretch

jobs:
  setup:
  executor: node
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
                cd server && npm i &&
                cd ../client && npm i
